# Copyright 2018 Cyface GmbH
# 
# This file is part of the Cyface Data Collector.
# 
# The Cyface Data Collector is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  
# The Cyface Data Collector is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Cyface Data Collector. If not, see <http://www.gnu.org/licenses/>.

version: "3"
services:
    # Mongo Database Container
    mongo-data:
      image: mongo:4.0.3
      networks:
        - cyface
      volumes:
        - ./data:/data/db
      user: ${CURRENT_UID}
        
    mongo-user:
      image: mongo:4.0.3
      networks:
        - cyface
      volumes:
        - ./user-data:/data/db
      user: ${CURRENT_UID}

    # The Cyface Collector API Container
    api:
      build: .
      ports:
        - "8080:8080"
      networks:
        - cyface
      volumes:
        - ./secrets:/app/secrets
      depends_on:
        - mongo-data
        - mongo-user
      # user: ${CURRENT_UID} <-- Does not work. Whyever. ???
        
    # Prometheus Metrics tool
    prometheus:
      build: prometheus
      networks:
        - cyface
      volumes:
        - ./prometheus/data:/prometheus
      user: ${CURRENT_UID}
        
    # Grafana Dashboard on Prometheus Data
    grafana:
      build: grafana
      ports:
        - 3000:3000
      networks:
        - cyface
      volumes:
        - ./grafana/data:/var/lib/grafana
        - ./grafana/logs:/var/log/grafana
      environment:
        - GF_SECURITY_ADMIN_USER=cyface-admin
        - GF_SECURITY_ADMIN_PASSWORD=cyface-admin@grafana
      user: ${CURRENT_UID}

networks:
    cyface:
