= Collector

image:https://img.shields.io/badge/vert.x-3.6.0--SNAPSHOT-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./gradlew clean test
```

To package your application:
```
./gradlew clean assemble
```

To run your application:
```
./gradlew clean run
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]

== Execution
This section describes how to execute the Cyface data collector.

=== Command Line Arguments
The Cyface data collector supports a few parameters to fine tune the runtime. All of these parameters also provide reasonable defaults for quick setup. In production you should change those values to fit your environment. The parameters are provided using the typical Vertx `-conf` parameter with a value in JSON notation. The following parameters are supported:

* keystore.jwt: The path of the keystore used to sign JWT keys. This defaults to the keystore available under `src/main/resources/keystore.jceks`, which you should never use in production.
* keystore.jwt.password: The password to access the JWT keystore file.
* keystore.tls: The path of the keystore used to encrypt HTTPS communication. This defaults to the keystore for localhost available under `src/main/resources/localhost.jks`. The default one will only work for a server reached using `localhost`. In production you will require your own file.
* keystore.tls.password: The password to access the keystore used for HTTPS communication.
* http.port: The port the API  is available at. This defaults to `8080`.
* mongo.userdb: Settings for a Mongo database storing credential information about all the users capable of logging into the system. This defaults to a Mongo database available at `mongodb://127.0.0.1:27017`. The value of this should be a JSON object configured as described https://vertx.io/docs/vertx-mongo-client/java/#_configuring_the_client[here]. In addition, if you use two different Mongo databases for credentials and data you should provide different values for the JSON key `data_source_name`.
* mongo.datadb: Settings for a Mongo database storing all data uploaded via the Cyface data collector. This defaults to a Mongo database available at `mongodb://127.0.0.1:27017`. The value of this should be a JSON object configured as described https://vertx.io/docs/vertx-mongo-client/java/#_configuring_the_client[here]. In addition, if you use two different Mongo databases for credentials and data you should provide different values for the JSON key `data_source_name`.

=== Running from IDE
To run directly from within your IDE you need to use the https://vertx.io/docs/vertx-core/java/#_the_vert_x_launcher[Vert.x launcher]. Just specify it as the main class in your launch configuration with the program argument `run de.cyface.collector.MainVerticle`.

=== Running from Docker
Simply run `docker-compose up` inside the root of this project. This brings up a Mongo database container and a container running the Cyface data collector API.

== TODO
* Setup Cluster
	* Vertx
	* MongoDb
* Finish multi part test

== Licensing
Copyright 2018 Cyface GmbH
 
This file is part of the Cyface Data Collector.

The Cyface Data Collector is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
  
The Cyface Data Collector is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the Cyface Data Collector.  If not, see <http://www.gnu.org/licenses/>.
