openapi: 3.0.2
info:
  title: Cyface Data Collector Management Interface
  description: This is the internal endpoint to manage a Cyface Data Collector
  version: 4.0.0
      
paths:
  /user:
    post:
      summary: Create a new user for this Cyface data collector
      operationId: addUser
      requestBody:
        description: The new users username and password.
        required: true
        content:
          'application/json':
            schema:
              type: object
              properties:
                username:
                  description: Name of the new user.
                  type: string
                password:
                  description: Password for the new user.
                  type: string
              required:
                - username
                - password
              example:
                username: admin
                password: secret
      responses:
        '201':
          description: User was created successfully.
        '400':
          description: The reques was malformed.

  /users:
    post:
      summary: Create multiple new users for this Cyface data collector
      operationId: addUsers
      requestBody:
        description: The new users username prefix and the number of users.
        required: true
        content:
          'application/json':
            schema:
              type: object
              properties:
                usernamePrefix:
                  description: Prefix used to generate the usernames.
                  type: string
                numberOfUsers:
                  description: Number of users to create (1-10000).
                  type: integer
              required:
                - usernamePrefix
                - numberOfUsers
              example:
                usernamePrefix: bulkUser
                numberOfUsers: 2
      responses:
        '201':
          description: Users were created successfully. Returns the credentials of the created users as JSON string in the format {"username1":"password1"}.
          headers:
            credentials:
              schema:
                type: string
                format: application/json
                properties:
                  username:
                    type: string
                    description: The generated username.
                  password:
                    type: string
                    description: The generated password.
              description: The credentials of the created users.
        '400':
          description: The reques was malformed.
