# Copyright 2018-2022 Cyface GmbH
#
# This file is part of the Cyface Data Collector.
#
# The Cyface Data Collector is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Cyface Data Collector is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Cyface Data Collector. If not, see <http://www.gnu.org/licenses/>.
#
# version 2.1.2

version: "3.7"
services:

  # Mongo Database Container
  mongo-data:
    container_name: collector_mongo-data
    image: mongo:4.4.4
    ports:
      - "127.0.0.1:27019:27017"
    volumes:
      - type: volume
        source: collector_mongo-data-db
        target: /data/db
    networks:
      - database
    environment:
      - MONGO_INITDB_DATABASE=cyface-data

  mongo-user:
    container_name: collector_mongo-user
    image: mongo:4.4.4
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - type: volume
        source: collector_mongo-user-db
        target: /data/db
      - type: bind
        source: ./init-scripts/mongo-user/
        target: /docker-entrypoint-initdb.d/
    networks:
      - database
    environment:
      MONGO_INITDB_DATABASE: cyface-user

  # The Cyface Collector API Container
  api:
    container_name: collector_api
    build: .
    image: data-collector:0.0.0
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:13371:13371"
    networks:
      - database
      - default
    volumes:
      - ./secrets:/app/secrets:ro # read only
      - ./logs:/app/logs
      - ./logback.xml:/app/logback.xml:ro # read only
      - ./file-uploads:/app/file-uploads # for debugging
    depends_on:
      - mongo-data
      - mongo-user
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
      - SALT_FILE=/app/secrets/salt

volumes:
  collector_mongo-data-db:
  collector_mongo-user-db:

networks:
  default:
    name: cyface-collector
    ipam:
      driver: default
      config:
        # Configure the IP Address range to not conflict with Deutsche Bahn WiFi
        - subnet: 172.72.0.1/24
        - subnet: 2001:3984:3989::/64
  # Shared docker network. Allows "exporter" docker container to access APIs without exposing them to the outside world
  database:
    name: cyface-collector_database
