# Copyright 2018 Cyface GmbH
# 
# This file is part of the Cyface Data Collector.
# 
# The Cyface Data Collector is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  
# The Cyface Data Collector is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Cyface Data Collector. If not, see <http://www.gnu.org/licenses/>.

# config file version
apiVersion: 1

# list of datasources that should be deleted from the
# database
# deleteDatasources:
#  - name: Prometheus
#    orgId: 1

# list of datasources to insert/update depending
# on what's available in the database
datasources:
   # <string, required> name of the datasource, Required
 - name: Prometheus
   # <string, required> datasource type. Required
   type: prometheus
   # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   # orgId: 1
   # <string> url
   url: http://prometheus:9090
   # <string> database password, if used
   # password:
   # <string> datase user, if used
   # user:
   # <string> database name, if used
   # database:
   # <bool> enable/disable basic auth
   # basicAuth:
   # <string> basic auth username
   # basicAuthUser:
   # <string> basic auth password
   # basicAuthPassword:
   # <bool> enable/disable with credentials headers
   # withCredentials
   # <bool> mark as default datasource. Max one per org
   isDefault: true
   # <map> fields that will be converted to json and stored in jsonData
   # jsonData:
     # graphiteVersion: "1.1"
     # tlsAuth: true
     # tlsAuthWithCACert: true
   # <string> json object of data that will be encrypted.
   # secureJsonData:
     # tlsCACert: "..."
     # tlsClientCert: "..."
     # tlsClientKey: "..."
   # version: 1
   # <bool> allow users to edit datasources from the UI.
   editable: false