title: Cyface Data Collector
baseUri: https://cyface.de/collector/api/v2
version: v3
securedBy:
- jwt
securitySchemes:
- jwt:
    description: All calls to this API require a valid JWT token.
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid JWT token.
          type: string
      responses:
        401:
          description: Bad or expired token. This can happen if the server revoked or expired an access token. To fix, you should reauthenticate the user.
        403:
          description: Token has no access to the requested resource.
    settings:
      authorizationUri: api/v2/login
      authorizationGrants:
      - token
/measurements:
  description: Measurements currently collected by the API.
  post:
    body:
      multipart/form-data:
        formParameters:
          fileToUpload:
            description: The file to be uploaded
            required: true
            type: file
          deviceId:
            required: true
            type: string
          measurementId:
            required: true
            type: string
          deviceType:
            required: true
            type: string
          osVersion:
            required: true
            type: string
    responses:
      201:
        description: If the file was successfully uploaded.
      400:
        description: Unknown error for example if Web server reports status -1 or the client experienced a synchronisation error.
      404:
        description: Resource does not exist
      409:
        description: The measurement from the device already exists on the server.
      422:
        description: The multipart request is erroneous. There for example is not exactly one file or a syntax error.
      500:
        description: Reported on any internal server error, such as the storage layer was not accessible.