openapi: 3.0.2
info:
  title: Cyface Data Collector
  description: This is a Cyface data collection endpoint, that receives traffic data from Cyface measurement devices, and stores them for further processing.
  version: 3.3.0
  
servers:
  - url: /api/v2

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
paths:
  /login:
    post:
      summary: Login to retrieve a new valid JWT Auth Token
      operationId: login
      requestBody:
        description: Valid credentials to log in to this Cyface Data Collector
        required: true
        content:
          'application/json':
            schema:
              type: object
              properties:
                username:
                  description: Name of a valid user within this instance of the Cyface data collector.
                  type: string
                password:
                  description: Password belonging to the provided user used to identify the user with the system.
                  type: string
              required:
                - username
                - password
              example:
                username: admin
                password: secret
      responses:
        '200':
          description: Your credentials were correct. The Authorization header contains a JWT key that is valid for 60 seconds to upload data.
          headers:
            Authorization:
              description: The generated JWT token.
              schema:
                type: string
                format: jwt
            content-length:
              description: The length of the generated JWT token in byte.
              schema:
                type: integer
                minimum: 0
        '401':
          description: The provided credentials were not correct
            
  /measurements:
    post:
      summary: Measurements currently collected by the API.
      operationId: uploadMeasurement
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          'multipart/form-data':
            schema:
              type: object
              properties:
                fileToUpload:
                  #description: The measured data in the Cyface binary format.
                  type: string
                  format: binary
                  example:
                    summary: An example upload in Cyface data format version 1
                    externalValue: 'data.ccyf'
                deviceId:
                  #description: The world wide unique identifier of the device that uploaded the data.
                  type: string
                  example: a
                measurementId:
                  #description: The device wide unique identifier of the uploaded measurement.
                  type: string
                  example: 1
                deviceType:
                  #description: The type of the device, that uploaded the data.
                  type: string
                  example: HTC Desire
                osVersion:
                  #description: The version of the device operating system.
                  type: string
                  example: 4.4.4
                appVersion:
                  type: string
                  example: 1.0.2
                length:
                  type: integer
                  format: int64
                  example: 468.429108633028
                locationCount:
                  type: number
                  format: double
                  example: 172
                startLocLat:
                  type: number
                  format: double
                  example: 51.05220494330958
                startLocLon:
                  type: number
                  format: double
                  example: 13.729234272626908
                startLocTS: 
                  type: integer
                  format: int64
                  example: 1551436825471
                endLocLat:
                  type: number
                  format: double
                  example: 51.05209006932662
                endLocLon:
                  type: number
                  format: double
                  example: 13.728697160271674
                endLocTS:
                  type: integer
                  format: int64
                  example: 1551436996091
              required:
                - fileToUpload
                - deviceId
                - measurementId
                - deviceType
                - osVersion
                - appVersion
                - length
                - locationCount
                - startLocLat
                - startLocLon
                - startLocTS
                - endLocLat
                - endLocLon
                - endLocTS
              
      responses:
        '201':
          description: If the file was successfully uploaded.
        '400':
          description: Unknown error for example if Web server reports status -1 or the client experienced a synchronisation error.
        '401':
          description: No Authorization information provided. This request requires a valid JWT token to continue.
        '403':
          description: Authorization information was provided, but the authorized user has no permission to post measurements.
        '409':
          description: The measurement from the device already exists on the server.
        '422':
          description: The multipart request is erroneous. There for example is not exactly one file or a syntax error.
        '500':
          description: Reported on any internal server error, such as the storage layer was not accessible.