openapi: 3.0.3
info:
  title: Cyface Data Collector
  description: This is a Cyface data collection endpoint, that receives traffic data from Cyface measurement devices, and stores them for further processing.
  version: 6.10.1
  
servers:
  - url: /api/v3

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
paths:
  /login:
    post:
      summary: Login to retrieve a new valid JWT Auth Token
      operationId: login
      requestBody:
        description: Valid credentials to log in to this Cyface Data Collector
        required: true
        content:
          'application/json':
            schema:
              type: object
              properties:
                username:
                  description: Name of a valid user within this instance of the Cyface data collector.
                  type: string
                password:
                  description: Password belonging to the provided user used to identify the user with the system.
                  type: string
              required:
                - username
                - password
            examples:
              registered:
                value:
                  username: guest@example.com
                  password: secret
              generated:
                value:
                  username: guest
                  password: secret
      responses:
        '200':
          description: Your credentials were correct. The Authorization header contains a JWT key that is valid for 60 seconds to upload data.
          headers:
            Authorization:
              description: The generated JWT token.
              schema:
                type: string
                format: jwt
            content-length:
              description: The length of the generated JWT token in byte.
              schema:
                type: integer
                minimum: 0
        '401':
          description: The provided credentials were not correct
        '428':
          description: The user account is not activated.
        '429':
          description: Too many requests in short succession
            
  /measurements:
    post:
      summary: Pre-request to ask for an upload session id.
      operationId: uploadMeasurementPreRequest
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: x-upload-content-length
          schema:
            type: string
            example: 123
      requestBody:
        required: true
        content:
          'application/json; charset=UTF-8':
            schema:
              type: object
              properties:
                deviceId:
                  #description: The worldwide unique identifier of the device that uploaded the data.
                  type: string
                  example: d329c6ec-2764-44b1-b56a-9e3506508424
                measurementId:
                  #description: The device wide unique identifier of the uploaded measurement.
                  type: string
                  example: 1
                deviceType:
                  #description: The type of the device, that uploaded the data.
                  type: string
                  example: HTC Desire
                osVersion:
                  #description: The version of the device operating system.
                  type: string
                  example: 4.4.4
                appVersion:
                  type: string
                  example: 1.0.2
                length:
                  type: integer
                  format: int64
                  example: 468.429108633028
                locationCount:
                  type: number
                  format: double
                  example: 172
                startLocLat:
                  type: number
                  format: double
                  example: 51.05220494330958
                startLocLon:
                  type: number
                  format: double
                  example: 13.729234272626908
                startLocTS: 
                  type: integer
                  format: int64
                  example: 1551436825471
                endLocLat:
                  type: number
                  format: double
                  example: 51.05209006932662
                endLocLon:
                  type: number
                  format: double
                  example: 13.728697160271674
                endLocTS:
                  type: integer
                  format: int64
                  example: 1551436996091
                modality:
                  type: string
                  example: BICYCLE
                formatVersion:
                  type: string
                  example: 3
              required:
                - fileToUpload
                - eventsFile
                - deviceId
                - measurementId
                - deviceType
                - osVersion
                - appVersion
                - length
                - locationCount
                - startLocLat
                - startLocLon
                - startLocTS
                - endLocLat
                - endLocLon
                - endLocTS
                - modality
                - formatVersion
      responses:
        '200':
          description: If the file may be uploaded.
          headers:
            Location:
              schema:
                type: string
                example: https://example.com/api/v3/measurements/(e9076dbc2c8f15dd26aa76b4b5b49595)/
              description: Endpoint to upload the measurement to.
            Content-Length:
              schema:
                type: string
                example: 0
              description: Only useful in when a resume position is returned by the server (not yet supported).
        '400':
          description: Unknown error for example if Web server reports status -1 or the client experienced a synchronisation error.
        '401':
          description: No Authorization information provided. This request requires a valid JWT token to continue.
        '403':
          description: Authorization information was provided, but the authorized user has no permission to post measurements.
        '409':
          description: The measurement from the device already exists on the server.
        '412':
          description: The server is not interested in the data, e.g. upload file too large or data from a location of no interest.
        '422':
          description: The request is erroneous. There for example is for example a syntax error.
        '429':
          description: Too many requests in too short succession.
        '500':
          description: Reported on any internal server error, such as the storage layer was not accessible.

  /measurements/({sessionId})/:
    put:
      summary: Measurement upload request.
      operationId: uploadMeasurement
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: sessionId
          required: true
          description: The upload session id received in the response `location` parameter of the pre-request.
          schema:
            type: string
          example:
            e9076dbc2c8f15dd26aa76b4b5b49595
        - in: header
          name: Content-Range
          required: true
          schema:
            type: string
            example: bytes 0-122/123
        - in: header
          name: deviceId
          required: true
          schema:
            type: string
            description: The worldwide unique identifier of the device that uploaded the data.
            example: d329c6ec-2764-44b1-b56a-9e3506508424
        - in: header
          name: measurementId
          required: true
          schema:
            type: string
            description: The device wide unique identifier of the uploaded measurement.
            example: 1
        - in: header
          name: deviceType
          required: true
          schema:
            type: string
            description: The type of the device, that uploaded the data.
            example: HTC Desire
        - in: header
          name: osVersion
          required: true
          schema:
            type: string
            description: The version of the device operating system.
            example: 4.4.4
        - in: header
          name: appVersion
          required: true
          schema:
            type: string
            example: 1.0.2
        - in: header
          name: length
          required: true
          schema:
            type: number
            format: double
            example: 468.429108633028
        - in: header
          name: locationCount
          required: true
          schema:
            type: integer
            format: int64
            example: 172
        - in: header
          name: startLocLat
          required: true
          schema:
            type: number
            format: double
            example: 51.05220494330958
        - in: header
          name: startLocLon
          required: true
          schema:
            type: number
            format: double
            example: 13.729234272626908
        - in: header
          name: startLocTS
          required: true
          schema:
            type: integer
            format: int64
            example: 1551436825471
        - in: header
          name: endLocLat
          required: true
          schema:
            type: number
            format: double
            example: 51.05209006932662
        - in: header
          name: endLocLon
          required: true
          schema:
            type: number
            format: double
            example: 13.728697160271674
        - in: header
          name: endLocTS
          required: true
          schema:
            type: integer
            format: int64
            example: 1551436996091
        - in: header
          name: modality
          required: true
          schema:
            type: string
            example: BICYCLE
        - in: header
          name: formatVersion
          required: true
          schema:
            type: string
            example: 3
      requestBody:
        required: true
        content:
          'application/octet-stream':
            schema:
              type: string
              format: binary

      responses:
        '201':
          description: When the upload was successful.
        '400':
          description: Unknown error for example if Web server reports status -1 or the client experienced a synchronisation error.
        '401':
          description: No Authorization information provided. This request requires a valid JWT token to continue.
        '403':
          description: Authorization information was provided, but the authorized user has no permission to post measurements.
        '409':
          description: The measurement from the device already exists on the server.
        '412':
          description: The server is not interested in the data, e.g. upload file too large or data from a location of no interest.
        '422':
          description: The request is erroneous. There for example is for example a syntax error.
        '429':
          description: Too many requests in too short succession.
        '500':
          description: Reported on any internal server error, such as the storage layer was not accessible.
