name: Cyface Data Collector

on: 
  pull_request:
  push:
    branches: 
      - dev
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean shadowJar check jacocoTestReport
    - name: Publish Latest to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cyfacede/collector
        username: ${{ screts.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
